// ============================================================
// Mission Export — QGroundControl, KML, ArduPilot Waypoints
// Export planned paths to various drone mission formats
// ============================================================

import type { Point, PathResult } from './algorithms';

// ── QGroundControl Mission Plan (.plan) ──────────────────────
export interface QGCMissionItem {
  autoContinue: boolean;
  command: number;
  doJumpId: number;
  frame: number;
  params: number[];
  type: string;
}

export interface QGCMissionPlan {
  fileType: string;
  geoFence: { circles: unknown[]; polygons: unknown[]; version: number };
  groundStation: string;
  mission: {
    cruiseSpeed: number;
    firmwareType: number;
    hoverSpeed: number;
    items: QGCMissionItem[];
    plannedHomePosition: number[];
    vehicleType: number;
    version: number;
  };
  rallyPoints: { points: unknown[]; version: number };
  version: number;
}

export function exportToQGC(
  path: Point[],
  options: {
    homePosition?: { lat: number; lng: number; alt: number };
    altitude?: number;
    speed?: number;
    pixelToGPS?: (p: Point) => { lat: number; lng: number };
  } = {}
): QGCMissionPlan {
  const {
    homePosition = { lat: 37.7749, lng: -122.4194, alt: 0 },
    altitude = 50,
    speed = 10,
    pixelToGPS = (p) => ({
      lat: homePosition.lat + p.y * 0.00001,
      lng: homePosition.lng + p.x * 0.00001,
    }),
  } = options;

  const items: QGCMissionItem[] = [
    // Takeoff
    {
      autoContinue: true,
      command: 22, // MAV_CMD_NAV_TAKEOFF
      doJumpId: 1,
      frame: 3,
      params: [0, 0, 0, 0, homePosition.lat, homePosition.lng, altitude],
      type: 'SimpleItem',
    },
  ];

  // Waypoints
  path.forEach((point, i) => {
    const gps = pixelToGPS(point);
    items.push({
      autoContinue: true,
      command: 16, // MAV_CMD_NAV_WAYPOINT
      doJumpId: i + 2,
      frame: 3,
      params: [0, 0, 0, 0, gps.lat, gps.lng, altitude],
      type: 'SimpleItem',
    });
  });

  // Return to launch
  items.push({
    autoContinue: true,
    command: 20, // MAV_CMD_NAV_RETURN_TO_LAUNCH
    doJumpId: items.length + 1,
    frame: 2,
    params: [0, 0, 0, 0, 0, 0, 0],
    type: 'SimpleItem',
  });

  return {
    fileType: 'Plan',
    geoFence: { circles: [], polygons: [], version: 2 },
    groundStation: 'SemtechDroneLab',
    mission: {
      cruiseSpeed: speed,
      firmwareType: 12, // PX4
      hoverSpeed: speed / 2,
      items,
      plannedHomePosition: [homePosition.lat, homePosition.lng, homePosition.alt],
      vehicleType: 2, // Quadrotor
      version: 2,
    },
    rallyPoints: { points: [], version: 2 },
    version: 1,
  };
}

// ── KML Export (Google Earth) ────────────────────────────────
export function exportToKML(
  path: Point[],
  options: {
    name?: string;
    description?: string;
    homePosition?: { lat: number; lng: number };
    altitude?: number;
    pixelToGPS?: (p: Point) => { lat: number; lng: number };
  } = {}
): string {
  const {
    name = 'Semtech Drone Mission',
    description = 'Autonomous flight path generated by Semtech Drone Lab',
    homePosition = { lat: 37.7749, lng: -122.4194 },
    altitude = 50,
    pixelToGPS = (p) => ({
      lat: homePosition.lat + p.y * 0.00001,
      lng: homePosition.lng + p.x * 0.00001,
    }),
  } = options;

  const coordinates = path
    .map((p) => {
      const gps = pixelToGPS(p);
      return `${gps.lng},${gps.lat},${altitude}`;
    })
    .join('\n            ');

  return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${escapeXml(name)}</name>
    <description>${escapeXml(description)}</description>
    <Style id="flightPath">
      <LineStyle>
        <color>ffff9900</color>
        <width>3</width>
      </LineStyle>
    </Style>
    <Style id="waypoint">
      <IconStyle>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/paddle/wht-circle.png</href>
        </Icon>
      </IconStyle>
    </Style>
    <Placemark>
      <name>Flight Path</name>
      <styleUrl>#flightPath</styleUrl>
      <LineString>
        <altitudeMode>relativeToGround</altitudeMode>
        <coordinates>
            ${coordinates}
        </coordinates>
      </LineString>
    </Placemark>
    ${path.map((p, i) => {
      const gps = pixelToGPS(p);
      return `<Placemark>
      <name>WP ${i + 1}</name>
      <styleUrl>#waypoint</styleUrl>
      <Point>
        <altitudeMode>relativeToGround</altitudeMode>
        <coordinates>${gps.lng},${gps.lat},${altitude}</coordinates>
      </Point>
    </Placemark>`;
    }).join('\n    ')}
  </Document>
</kml>`;
}

// ── ArduPilot Waypoint File (.waypoints) ─────────────────────
export function exportToArduPilot(
  path: Point[],
  options: {
    homePosition?: { lat: number; lng: number; alt: number };
    altitude?: number;
    pixelToGPS?: (p: Point) => { lat: number; lng: number };
  } = {}
): string {
  const {
    homePosition = { lat: 37.7749, lng: -122.4194, alt: 0 },
    altitude = 50,
    pixelToGPS = (p) => ({
      lat: homePosition.lat + p.y * 0.00001,
      lng: homePosition.lng + p.x * 0.00001,
    }),
  } = options;

  const lines: string[] = [
    'QGC WPL 110', // File header
    // Home position: seq, current, frame, command, p1-p4, lat, lng, alt, autocontinue
    `0\t1\t0\t16\t0\t0\t0\t0\t${homePosition.lat}\t${homePosition.lng}\t${homePosition.alt}\t1`,
  ];

  // Takeoff
  lines.push(`1\t0\t3\t22\t0\t0\t0\t0\t${homePosition.lat}\t${homePosition.lng}\t${altitude}\t1`);

  // Waypoints
  path.forEach((point, i) => {
    const gps = pixelToGPS(point);
    const seq = i + 2;
    lines.push(`${seq}\t0\t3\t16\t0\t0\t0\t0\t${gps.lat}\t${gps.lng}\t${altitude}\t1`);
  });

  // RTL
  const rtlSeq = path.length + 2;
  lines.push(`${rtlSeq}\t0\t3\t20\t0\t0\t0\t0\t0\t0\t0\t1`);

  return lines.join('\n');
}

// ── JSON Export (with metadata) ──────────────────────────────
export function exportToJSON(result: PathResult, metadata: Record<string, unknown> = {}): string {
  return JSON.stringify({
    format: 'semtech-drone-v1',
    exportedAt: new Date().toISOString(),
    path: result.path,
    pathLength: result.path.length,
    totalCost: result.cost,
    exploredCells: result.explored.length,
    ...metadata,
  }, null, 2);
}

// ── GPX Export (GPS Exchange Format) ─────────────────────────
export function exportToGPX(
  path: Point[],
  options: {
    name?: string;
    homePosition?: { lat: number; lng: number };
    altitude?: number;
    pixelToGPS?: (p: Point) => { lat: number; lng: number };
  } = {}
): string {
  const {
    name = 'Semtech Drone Mission',
    homePosition = { lat: 37.7749, lng: -122.4194 },
    altitude = 50,
    pixelToGPS = (p) => ({
      lat: homePosition.lat + p.y * 0.00001,
      lng: homePosition.lng + p.x * 0.00001,
    }),
  } = options;

  const trackpoints = path
    .map((p) => {
      const gps = pixelToGPS(p);
      return `      <trkpt lat="${gps.lat}" lon="${gps.lng}"><ele>${altitude}</ele></trkpt>`;
    })
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="SemtechDroneLab">
  <metadata>
    <name>${escapeXml(name)}</name>
    <time>${new Date().toISOString()}</time>
  </metadata>
  <trk>
    <name>${escapeXml(name)}</name>
    <trkseg>
${trackpoints}
    </trkseg>
  </trk>
</gpx>`;
}

// ── Helper to trigger download ───────────────────────────────
export function downloadFile(content: string, filename: string, mimeType: string = 'application/octet-stream') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
